Regenerate

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.285 .
+# From configure.in Revision: 1.287 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.49d.
 #
@@ -9273,7 +9273,7 @@ gmp_mpn_functions_optional="copyi copyd com_n		\
   gcd_finda invert_limb sqr_diagonal"
 
 gmp_mpn_functions="$extra_functions inlines add_n sub_n mul_1 addmul_1   \
-  submul_1 lshift rshift diveby3 divis divrem divrem_1 divrem_2            \
+  submul_1 lshift rshift dive_1 diveby3 divis divrem divrem_1 divrem_2     \
   mod_1 mode1o pre_mod_1 dump                                              \
   mul mul_fft mul_n mul_basecase sqr_basecase random                       \
   random2 sqrtrem get_str set_str scan0 scan1 popcount hamdist cmp perfsqr \
@@ -11014,7 +11014,7 @@ echo "define(\`__CONFIG_M4_INCLUDED__')" >> $gmp_configm4
 # FIXME: Upcoming version of autoconf/automake may not like broken lines.
 #        Right now automake isn't accepting the new AC_CONFIG_FILES scheme.
 
-ac_config_files="$ac_config_files Makefile mpbsd/Makefile mpf/Makefile mpfr/Makefile mpn/Makefile mpq/Makefile mpz/Makefile mpfr/tests/Makefile tests/Makefile tests/devel/Makefile tests/mpbsd/Makefile tests/mpf/Makefile tests/mpq/Makefile tests/mpz/Makefile tests/rand/Makefile tune/Makefile demos/Makefile demos/calc/Makefile demos/expr/Makefile gmp.h:gmp-h.in mp.h:mp-h.in demos/expr/expr-impl.h:demos/expr/expr-impl-h.in"
+ac_config_files="$ac_config_files Makefile mpbsd/Makefile mpf/Makefile mpfr/Makefile mpn/Makefile mpq/Makefile mpz/Makefile mpfr/tests/Makefile tests/Makefile tests/devel/Makefile tests/mpbsd/Makefile tests/mpf/Makefile tests/mpn/Makefile tests/mpq/Makefile tests/mpz/Makefile tests/rand/Makefile tune/Makefile demos/Makefile demos/calc/Makefile demos/expr/Makefile gmp.h:gmp-h.in mp.h:mp-h.in demos/expr/expr-impl.h:demos/expr/expr-impl-h.in"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -11315,6 +11315,7 @@ Try \`$0 --help' for more information." >&2;}
   'tests/devel/Makefile' ) CONFIG_FILES="$CONFIG_FILES tests/devel/Makefile" ;;
   'tests/mpbsd/Makefile' ) CONFIG_FILES="$CONFIG_FILES tests/mpbsd/Makefile" ;;
   'tests/mpf/Makefile' ) CONFIG_FILES="$CONFIG_FILES tests/mpf/Makefile" ;;
+  'tests/mpn/Makefile' ) CONFIG_FILES="$CONFIG_FILES tests/mpn/Makefile" ;;
   'tests/mpq/Makefile' ) CONFIG_FILES="$CONFIG_FILES tests/mpq/Makefile" ;;
   'tests/mpz/Makefile' ) CONFIG_FILES="$CONFIG_FILES tests/mpz/Makefile" ;;
   'tests/rand/Makefile' ) CONFIG_FILES="$CONFIG_FILES tests/rand/Makefile" ;;
@@ -11332,12 +11333,12 @@ Try \`$0 --help' for more information." >&2;}
   'config.h' ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config.in" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:11335: error: unrecognized option: $1
+  -*) { { echo "$as_me:11336: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:11340: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:11341: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -11621,7 +11622,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:11624: creating $ac_file" >&5
+    { echo "$as_me:11625: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -11639,7 +11640,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]* | ?:[\\/]*)
          # Absolute
-         test -f "$f" || { { echo "$as_me:11642: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11643: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11652,7 +11653,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11655: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11656: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11713,7 +11714,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:11716: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:11717: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -11724,7 +11725,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]* | ?:[\\/]*)
          # Absolute
-         test -f "$f" || { { echo "$as_me:11727: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11728: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11737,7 +11738,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11740: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11741: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11854,7 +11855,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:11857: $ac_file is unchanged" >&5
+      { echo "$as_me:11858: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -11905,11 +11906,11 @@ for ac_file in : $CONFIG_LINKS; do test "x$ac_file" = x: && continue
   ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
   ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
 
-  { echo "$as_me:11908: linking $srcdir/$ac_source to $ac_dest" >&5
+  { echo "$as_me:11909: linking $srcdir/$ac_source to $ac_dest" >&5
 echo "$as_me: linking $srcdir/$ac_source to $ac_dest" >&6;}
 
   if test ! -r $srcdir/$ac_source; then
-    { { echo "$as_me:11912: error: $srcdir/$ac_source: File not found" >&5
+    { { echo "$as_me:11913: error: $srcdir/$ac_source: File not found" >&5
 echo "$as_me: error: $srcdir/$ac_source: File not found" >&2;}
    { (exit 1); exit 1; }; }
   fi
@@ -11959,7 +11960,7 @@ done; }
   # Make a symlink if possible; otherwise try a hard link.
   ln -s $ac_rel_source $ac_dest 2>/dev/null ||
     ln $srcdir/$ac_source $ac_dest ||
-    { { echo "$as_me:11962: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
+    { { echo "$as_me:11963: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
 echo "$as_me: error: cannot link $ac_dest to $srcdir/$ac_source" >&2;}
    { (exit 1); exit 1; }; }
 done
