Regenerate for:         * Makefile.am, configure.in: Temporarily remove mpfr, just leave a         README.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.343 .
+# From configure.in Revision: 1.344 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -19725,7 +19725,7 @@ echo "define(\`__CONFIG_M4_INCLUDED__')" >> $gmp_configm4
 # FIXME: Upcoming version of autoconf/automake may not like broken lines.
 #        Right now automake isn't accepting the new AC_CONFIG_FILES scheme.
 
-ac_config_files="$ac_config_files Makefile mpbsd/Makefile mpf/Makefile mpfr/Makefile mpn/Makefile mpq/Makefile mpz/Makefile printf/Makefile scanf/Makefile cxx/Makefile mpfr/tests/Makefile tests/Makefile tests/devel/Makefile tests/mpbsd/Makefile tests/mpf/Makefile tests/mpn/Makefile tests/mpq/Makefile tests/mpz/Makefile tests/rand/Makefile tests/misc/Makefile tests/cxx/Makefile tune/Makefile demos/Makefile demos/calc/Makefile demos/expr/Makefile gmp.h:gmp-h.in mp.h:mp-h.in demos/expr/expr-impl.h:demos/expr/expr-impl-h.in"
+ac_config_files="$ac_config_files Makefile mpbsd/Makefile mpf/Makefile mpn/Makefile mpq/Makefile mpz/Makefile printf/Makefile scanf/Makefile cxx/Makefile tests/Makefile tests/devel/Makefile tests/mpbsd/Makefile tests/mpf/Makefile tests/mpn/Makefile tests/mpq/Makefile tests/mpz/Makefile tests/rand/Makefile tests/misc/Makefile tests/cxx/Makefile tune/Makefile demos/Makefile demos/calc/Makefile demos/expr/Makefile gmp.h:gmp-h.in mp.h:mp-h.in demos/expr/expr-impl.h:demos/expr/expr-impl-h.in"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -20051,14 +20051,12 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "mpbsd/Makefile" ) CONFIG_FILES="$CONFIG_FILES mpbsd/Makefile" ;;
   "mpf/Makefile" ) CONFIG_FILES="$CONFIG_FILES mpf/Makefile" ;;
-  "mpfr/Makefile" ) CONFIG_FILES="$CONFIG_FILES mpfr/Makefile" ;;
   "mpn/Makefile" ) CONFIG_FILES="$CONFIG_FILES mpn/Makefile" ;;
   "mpq/Makefile" ) CONFIG_FILES="$CONFIG_FILES mpq/Makefile" ;;
   "mpz/Makefile" ) CONFIG_FILES="$CONFIG_FILES mpz/Makefile" ;;
   "printf/Makefile" ) CONFIG_FILES="$CONFIG_FILES printf/Makefile" ;;
   "scanf/Makefile" ) CONFIG_FILES="$CONFIG_FILES scanf/Makefile" ;;
   "cxx/Makefile" ) CONFIG_FILES="$CONFIG_FILES cxx/Makefile" ;;
-  "mpfr/tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES mpfr/tests/Makefile" ;;
   "tests/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
   "tests/devel/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/devel/Makefile" ;;
   "tests/mpbsd/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests/mpbsd/Makefile" ;;
@@ -20080,7 +20078,7 @@ do
   "gmp-mparam.h" ) CONFIG_LINKS="$CONFIG_LINKS gmp-mparam.h:mpn/$tmp_dir/gmp-mparam.h" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config.in" ;;
-  *) { { echo "$as_me:20083: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:20081: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -20368,7 +20366,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:20371: creating $ac_file" >&5
+    { echo "$as_me:20369: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -20386,7 +20384,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20389: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20387: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20399,7 +20397,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20402: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20400: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20460,7 +20458,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:20463: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:20461: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -20471,7 +20469,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20474: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20472: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20484,7 +20482,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20487: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20485: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -20601,7 +20599,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:20604: $ac_file is unchanged" >&5
+      { echo "$as_me:20602: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -20658,11 +20656,11 @@ for ac_file in : $CONFIG_LINKS; do test "x$ac_file" = x: && continue
   ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
   ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
 
-  { echo "$as_me:20661: linking $srcdir/$ac_source to $ac_dest" >&5
+  { echo "$as_me:20659: linking $srcdir/$ac_source to $ac_dest" >&5
 echo "$as_me: linking $srcdir/$ac_source to $ac_dest" >&6;}
 
   if test ! -r $srcdir/$ac_source; then
-    { { echo "$as_me:20665: error: $srcdir/$ac_source: File not found" >&5
+    { { echo "$as_me:20663: error: $srcdir/$ac_source: File not found" >&5
 echo "$as_me: error: $srcdir/$ac_source: File not found" >&2;}
    { (exit 1); exit 1; }; }
   fi
@@ -20712,7 +20710,7 @@ done; }
   # Make a symlink if possible; otherwise try a hard link.
   ln -s $ac_rel_source $ac_dest 2>/dev/null ||
     ln $srcdir/$ac_source $ac_dest ||
-    { { echo "$as_me:20715: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
+    { { echo "$as_me:20713: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
 echo "$as_me: error: cannot link $ac_dest to $srcdir/$ac_source" >&2;}
    { (exit 1); exit 1; }; }
 done
