Require operating system specification for cpus where assembly syntax differs between system.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -11,7 +11,11 @@ srcname="GNU Multi-Precision library"
 # per-target:
 
 case "${target}" in
-  sparc8* | microsparc*)
+  sparc*-*-none | supersparc*-*-none | ultrasparc*-*-none | microsparc*-*-none | \
+  i[56]86*-*-* | pentium-*-* | pentiumpro-*-*)
+    echo "*** Operating system specification required for this cpu." 1>&2
+    exit 1;;
+  sparc9-*-* | sparc64*-*-* | ultrasparc*-*-* | sparc8-*-* | microsparc*-*-*)
     if [ x$with_gcc != xno ]
     then
       target_makefile_frag=config/mt-sprc8-gcc
@@ -31,5 +35,4 @@ case "${target}" in
     ;;
   *-*-linux*)
     target_makefile_frag=config/mt-linux ;;
-    
 esac
