Regenerate for: A better effort at:         * configure.in: Add --with-readline, AC_PROG_YACC and AM_PROG_LEX.         * configure.in: Put demos/expr configs in expr-config.h.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.352 .
+# From configure.in Revision: 1.353 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -19907,12 +19907,16 @@ EOF
 esac
 
 # Configs for demos/calc directory
-
-		    		    		    ac_config_headers="$ac_config_headers demos/calc/calc-config.h:demos/calc/calc-config-h.in"
+#
+# AC_SUBST is used here since with AM_CONFIG_HEADER automake would put
+# demos/calc in the default $(DEFAULT_INCLUDES) for every directory,
+# which would look very strange.  Likewise demos/expr below.
+#
+ac_config_files="$ac_config_files demos/calc/calc-config.h:demos/calc/calc-config-h.in"
 
 use_readline=$with_readline
 if test $with_readline = detect; then
-  echo "$as_me:19915: checking for readline in -lreadline" >&5
+  echo "$as_me:19919: checking for readline in -lreadline" >&5
 echo $ECHO_N "checking for readline in -lreadline... $ECHO_C" >&6
 if test "${ac_cv_lib_readline_readline+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19920,7 +19924,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lreadline  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 19923 "configure"
+#line 19927 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -19939,16 +19943,16 @@ readline ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:19942: \"$ac_link\"") >&5
+if { (eval echo "$as_me:19946: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:19945: \$? = $ac_status" >&5
+  echo "$as_me:19949: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:19948: \"$ac_try\"") >&5
+  { (eval echo "$as_me:19952: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:19951: \$? = $ac_status" >&5
+  echo "$as_me:19955: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_readline_readline=yes
 else
@@ -19959,7 +19963,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:19962: result: $ac_cv_lib_readline_readline" >&5
+echo "$as_me:19966: result: $ac_cv_lib_readline_readline" >&5
 echo "${ECHO_T}$ac_cv_lib_readline_readline" >&6
 if test $ac_cv_lib_readline_readline = yes; then
   use_readline=yes
@@ -19967,19 +19971,18 @@ fi
 
 fi
 if test $use_readline = yes; then
-
-cat >>confdefs.h <<\EOF
-#define WITH_READLINE 1
-EOF
+  WITH_READLINE_01=1
 
   LIBREADLINE=-lreadline
 
+else
+  WITH_READLINE_01=0
 fi
 for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:19982: checking for $ac_word" >&5
+echo "$as_me:19985: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_YACC+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19994,7 +19997,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_YACC="$ac_prog"
-echo "$as_me:19997: found $ac_dir/$ac_word" >&5
+echo "$as_me:20000: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -20002,10 +20005,10 @@ fi
 fi
 YACC=$ac_cv_prog_YACC
 if test -n "$YACC"; then
-  echo "$as_me:20005: result: $YACC" >&5
+  echo "$as_me:20008: result: $YACC" >&5
 echo "${ECHO_T}$YACC" >&6
 else
-  echo "$as_me:20008: result: no" >&5
+  echo "$as_me:20011: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -20017,7 +20020,7 @@ for ac_prog in flex lex
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:20020: checking for $ac_word" >&5
+echo "$as_me:20023: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_LEX+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20032,7 +20035,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_LEX="$ac_prog"
-echo "$as_me:20035: found $ac_dir/$ac_word" >&5
+echo "$as_me:20038: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -20040,10 +20043,10 @@ fi
 fi
 LEX=$ac_cv_prog_LEX
 if test -n "$LEX"; then
-  echo "$as_me:20043: result: $LEX" >&5
+  echo "$as_me:20046: result: $LEX" >&5
 echo "${ECHO_T}$LEX" >&6
 else
-  echo "$as_me:20046: result: no" >&5
+  echo "$as_me:20049: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -20055,7 +20058,7 @@ for ac_prog in flex lex
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:20058: checking for $ac_word" >&5
+echo "$as_me:20061: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_LEX+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20070,7 +20073,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_LEX="$ac_prog"
-echo "$as_me:20073: found $ac_dir/$ac_word" >&5
+echo "$as_me:20076: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -20078,10 +20081,10 @@ fi
 fi
 LEX=$ac_cv_prog_LEX
 if test -n "$LEX"; then
-  echo "$as_me:20081: result: $LEX" >&5
+  echo "$as_me:20084: result: $LEX" >&5
 echo "${ECHO_T}$LEX" >&6
 else
-  echo "$as_me:20084: result: no" >&5
+  echo "$as_me:20087: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -20091,7 +20094,7 @@ test -n "$LEX" || LEX=":"
 
 if test -z "$LEXLIB"
 then
-  echo "$as_me:20094: checking for yywrap in -lfl" >&5
+  echo "$as_me:20097: checking for yywrap in -lfl" >&5
 echo $ECHO_N "checking for yywrap in -lfl... $ECHO_C" >&6
 if test "${ac_cv_lib_fl_yywrap+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20099,7 +20102,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lfl  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 20102 "configure"
+#line 20105 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -20118,16 +20121,16 @@ yywrap ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:20121: \"$ac_link\"") >&5
+if { (eval echo "$as_me:20124: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:20124: \$? = $ac_status" >&5
+  echo "$as_me:20127: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:20127: \"$ac_try\"") >&5
+  { (eval echo "$as_me:20130: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:20130: \$? = $ac_status" >&5
+  echo "$as_me:20133: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_fl_yywrap=yes
 else
@@ -20138,12 +20141,12 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:20141: result: $ac_cv_lib_fl_yywrap" >&5
+echo "$as_me:20144: result: $ac_cv_lib_fl_yywrap" >&5
 echo "${ECHO_T}$ac_cv_lib_fl_yywrap" >&6
 if test $ac_cv_lib_fl_yywrap = yes; then
   LEXLIB="-lfl"
 else
-  echo "$as_me:20146: checking for yywrap in -ll" >&5
+  echo "$as_me:20149: checking for yywrap in -ll" >&5
 echo $ECHO_N "checking for yywrap in -ll... $ECHO_C" >&6
 if test "${ac_cv_lib_l_yywrap+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20151,7 +20154,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-ll  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 20154 "configure"
+#line 20157 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -20170,16 +20173,16 @@ yywrap ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:20173: \"$ac_link\"") >&5
+if { (eval echo "$as_me:20176: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:20176: \$? = $ac_status" >&5
+  echo "$as_me:20179: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:20179: \"$ac_try\"") >&5
+  { (eval echo "$as_me:20182: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:20182: \$? = $ac_status" >&5
+  echo "$as_me:20185: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_l_yywrap=yes
 else
@@ -20190,7 +20193,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:20193: result: $ac_cv_lib_l_yywrap" >&5
+echo "$as_me:20196: result: $ac_cv_lib_l_yywrap" >&5
 echo "${ECHO_T}$ac_cv_lib_l_yywrap" >&6
 if test $ac_cv_lib_l_yywrap = yes; then
   LEXLIB="-ll"
@@ -20201,7 +20204,7 @@ fi
 fi
 
 if test "x$LEX" != "x:"; then
-  echo "$as_me:20204: checking lex output file root" >&5
+  echo "$as_me:20207: checking lex output file root" >&5
 echo $ECHO_N "checking lex output file root... $ECHO_C" >&6
 if test "${ac_cv_prog_lex_root+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20215,16 +20218,16 @@ if test -f lex.yy.c; then
 elif test -f lexyy.c; then
   ac_cv_prog_lex_root=lexyy
 else
-  { { echo "$as_me:20218: error: cannot find output from $LEX; giving up" >&5
+  { { echo "$as_me:20221: error: cannot find output from $LEX; giving up" >&5
 echo "$as_me: error: cannot find output from $LEX; giving up" >&2;}
    { (exit 1); exit 1; }; }
 fi
 fi
-echo "$as_me:20223: result: $ac_cv_prog_lex_root" >&5
+echo "$as_me:20226: result: $ac_cv_prog_lex_root" >&5
 echo "${ECHO_T}$ac_cv_prog_lex_root" >&6
 LEX_OUTPUT_ROOT=$ac_cv_prog_lex_root
 
-echo "$as_me:20227: checking whether yytext is a pointer" >&5
+echo "$as_me:20230: checking whether yytext is a pointer" >&5
 echo $ECHO_N "checking whether yytext is a pointer... $ECHO_C" >&6
 if test "${ac_cv_prog_lex_yytext_pointer+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20240,16 +20243,16 @@ cat >conftest.$ac_ext <<_ACEOF
 `cat $LEX_OUTPUT_ROOT.c`
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:20243: \"$ac_link\"") >&5
+if { (eval echo "$as_me:20246: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:20246: \$? = $ac_status" >&5
+  echo "$as_me:20249: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:20249: \"$ac_try\"") >&5
+  { (eval echo "$as_me:20252: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:20252: \$? = $ac_status" >&5
+  echo "$as_me:20255: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_prog_lex_yytext_pointer=yes
 else
@@ -20261,7 +20264,7 @@ LIBS=$ac_save_LIBS
 rm -f "${LEX_OUTPUT_ROOT}.c"
 
 fi
-echo "$as_me:20264: result: $ac_cv_prog_lex_yytext_pointer" >&5
+echo "$as_me:20267: result: $ac_cv_prog_lex_yytext_pointer" >&5
 echo "${ECHO_T}$ac_cv_prog_lex_yytext_pointer" >&6
 if test $ac_cv_prog_lex_yytext_pointer = yes; then
 
@@ -20274,15 +20277,13 @@ fi
 fi
 
 # Configs for demos/expr directory
-
-		    		    		    ac_config_headers="$ac_config_headers demos/expr/expr-config.h:demos/expr/expr-config-h.in"
+ac_config_files="$ac_config_files demos/expr/expr-config.h:demos/expr/expr-config-h.in"
 
 if test $enable_mpfr = yes; then
+  HAVE_MPFR_01=1
 
-cat >>confdefs.h <<\EOF
-#define HAVE_MPFR 1
-EOF
-
+else
+  HAVE_MPFR_01=0
 fi
 
 # Create config.m4.
@@ -20393,7 +20394,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:20396: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:20397: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -20572,7 +20573,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:20575: error: ambiguous option: $1
+    { { echo "$as_me:20576: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -20591,7 +20592,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:20594: error: unrecognized option: $1
+  -*) { { echo "$as_me:20595: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -20636,6 +20637,8 @@ for ac_config_target in $ac_config_targets
 do
   case "$ac_config_target" in
   # Handling of arguments.
+  "demos/calc/calc-config.h" ) CONFIG_FILES="$CONFIG_FILES demos/calc/calc-config.h:demos/calc/calc-config-h.in" ;;
+  "demos/expr/expr-config.h" ) CONFIG_FILES="$CONFIG_FILES demos/expr/expr-config.h:demos/expr/expr-config-h.in" ;;
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "mpbsd/Makefile" ) CONFIG_FILES="$CONFIG_FILES mpbsd/Makefile" ;;
   "mpf/Makefile" ) CONFIG_FILES="$CONFIG_FILES mpf/Makefile" ;;
@@ -20667,9 +20670,7 @@ do
   "gmp-mparam.h" ) CONFIG_LINKS="$CONFIG_LINKS gmp-mparam.h:mpn/$tmp_dir/gmp-mparam.h" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config.in" ;;
-  "demos/calc/calc-config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS demos/calc/calc-config.h:demos/calc/calc-config-h.in" ;;
-  "demos/expr/expr-config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS demos/expr/expr-config.h:demos/expr/expr-config-h.in" ;;
-  *) { { echo "$as_me:20672: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:20673: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -20842,11 +20843,13 @@ s,@mpn_objects@,$mpn_objects,;t t
 s,@mpn_objs_in_libgmp@,$mpn_objs_in_libgmp,;t t
 s,@gmp_srclinks@,$gmp_srclinks,;t t
 s,@TUNE_SQR_OBJ@,$TUNE_SQR_OBJ,;t t
+s,@WITH_READLINE_01@,$WITH_READLINE_01,;t t
 s,@LIBREADLINE@,$LIBREADLINE,;t t
 s,@YACC@,$YACC,;t t
 s,@LEX@,$LEX,;t t
 s,@LEXLIB@,$LEXLIB,;t t
 s,@LEX_OUTPUT_ROOT@,$LEX_OUTPUT_ROOT,;t t
+s,@HAVE_MPFR_01@,$HAVE_MPFR_01,;t t
 CEOF
 
 EOF
@@ -20961,7 +20964,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:20964: creating $ac_file" >&5
+    { echo "$as_me:20967: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -20979,7 +20982,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:20982: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:20985: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -20992,7 +20995,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:20995: error: cannot find input file: $f" >&5
+           { { echo "$as_me:20998: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -21053,7 +21056,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:21056: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:21059: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -21064,7 +21067,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:21067: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:21070: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -21077,7 +21080,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:21080: error: cannot find input file: $f" >&5
+           { { echo "$as_me:21083: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -21194,7 +21197,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:21197: $ac_file is unchanged" >&5
+      { echo "$as_me:21200: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -21238,12 +21241,6 @@ done; }
     config.h ) # update the timestamp
 echo timestamp >"./stamp-h1"
  ;;
-    demos/calc/calc-config.h ) # update the timestamp
-echo timestamp >"demos/calc/stamp-h1"
- ;;
-    demos/expr/expr-config.h ) # update the timestamp
-echo timestamp >"demos/expr/stamp-h1"
- ;;
   esac
 done
 EOF
@@ -21257,11 +21254,11 @@ for ac_file in : $CONFIG_LINKS; do test "x$ac_file" = x: && continue
   ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
   ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
 
-  { echo "$as_me:21260: linking $srcdir/$ac_source to $ac_dest" >&5
+  { echo "$as_me:21257: linking $srcdir/$ac_source to $ac_dest" >&5
 echo "$as_me: linking $srcdir/$ac_source to $ac_dest" >&6;}
 
   if test ! -r $srcdir/$ac_source; then
-    { { echo "$as_me:21264: error: $srcdir/$ac_source: File not found" >&5
+    { { echo "$as_me:21261: error: $srcdir/$ac_source: File not found" >&5
 echo "$as_me: error: $srcdir/$ac_source: File not found" >&2;}
    { (exit 1); exit 1; }; }
   fi
@@ -21311,7 +21308,7 @@ done; }
   # Make a symlink if possible; otherwise try a hard link.
   ln -s $ac_rel_source $ac_dest 2>/dev/null ||
     ln $srcdir/$ac_source $ac_dest ||
-    { { echo "$as_me:21314: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
+    { { echo "$as_me:21311: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
 echo "$as_me: error: cannot link $ac_dest to $srcdir/$ac_source" >&2;}
    { (exit 1); exit 1; }; }
 done
