* mpfr/*, aclocal.m4, config.in, configure: Update to mpfr cvs         2003-01-03.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24396,7 +24396,8 @@ case $host in
 esac
 
 
-for ac_func in strcasecmp
+
+for ac_func in strcasecmp strncasecmp
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -24746,6 +24747,60 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking for isnan" >&5
+echo $ECHO_N "checking for isnan... $ECHO_C" >&6
+if test "${mpfr_cv_have_isnan+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <math.h>
+int
+main ()
+{
+isnan(0.0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  mpfr_cv_have_isnan=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+mpfr_cv_have_isnan=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+fi
+echo "$as_me:$LINENO: result: $mpfr_cv_have_isnan" >&5
+echo "${ECHO_T}$mpfr_cv_have_isnan" >&6
+if test "$mpfr_cv_have_isnan" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define MPFR_HAVE_ISNAN 1
+_ACEOF
+
+fi
+
 
 for ac_func in lrand48
 do
@@ -25020,6 +25075,60 @@ if test "$mpfr_cv_have_denorms" = "yes"; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_DENORMS 1
+_ACEOF
+
+fi
+
+echo "$as_me:$LINENO: checking for HUGE_VAL" >&5
+echo $ECHO_N "checking for HUGE_VAL... $ECHO_C" >&6
+if test "${mpfr_cv_have_huge_val+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <math.h>
+int
+main ()
+{
+HUGE_VAL;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  mpfr_cv_have_huge_val=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+mpfr_cv_have_huge_val=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+
+fi
+echo "$as_me:$LINENO: result: $mpfr_cv_have_huge_val" >&5
+echo "${ECHO_T}$mpfr_cv_have_huge_val" >&6
+if test "$mpfr_cv_have_huge_val" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_HUGE_VAL 1
 _ACEOF
 
 fi
